version: "3"
services:
	db:
		image: postgres
		restart: always
		environment:
			POSTGRES_USER: "pguser"
			POSTGRES_PASSWORD: "pgpassword"
			POSTGRES_DB: "pgdb"
	manager:
		context: .
		dockerfile: .
		ports:
			- 5432:5432